services:
  - type: web
    name: piano-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn s:app
    envVars:
      - name: PORT
        value: 10000
      - name: PYTHON_VERSION
        value: 3.9.16 